{% set name = "nolearn" %}
{% set version = "0.6.1" %}
{% set python_min = "2.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/nolearn-{{ version }}.tar.gz
  sha256: bab2dc2aeb9560264791298f1d206b78fd9b345cecdd500b34f469d367765158

build:
  number: 2
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - joblib
    - lasagne
    - python >={{ python_min }}
    - scikit-learn <0.20
    - tabulate
    - theano

test:
  imports:
    - nolearn
    - nolearn.lasagne
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/dnouri/nolearn
  summary: scikit-learn compatible neural network library
  doc_url: https://pythonhosted.org/nolearn/
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jfy133
